---
- hosts: gcpdemo0
  gather_facts: no

  vars:
    project_id: "{{ lookup('env', 'GCE_PROJECT') }}"
    credentials_file: "{{ lookup('env', 'GCE_PEM_FILE_PATH') }}"
    service_account_email: "{{ lookup('env', 'GCE_EMAIL') }}"

  tasks:
    - name: Create DNS zone
      gcdns_zone:
        zone: ansiblemeetup.com
        project_id: "{{ project_id }}"
        credentials_file: "{{ credentials_file }}"
        service_account_email: "{{ service_account_email }}"
      delegate_to: localhost

    - name: Create DNS record
      gcdns_record:
        record: "{{ inventory_hostname }}.ansiblemeetup.com"
        zone: ansiblemeetup.com
        type: A
        value: "{{ ansible_ssh_host }}"
        project_id: "{{ project_id }}"
        credentials_file: "{{ credentials_file }}"
        service_account_email: "{{ service_account_email }}"
      delegate_to: localhost
