---
- name: Create new GCE instances for demo
  hosts: localhost
  gather_facts: no
  connection: local

  vars:
    instances:
      - gcpdemo0
      - gcpdemo1
    machine_type: g1-small # Tiny machine
    image: centos-7
    project_id: "{{ lookup('env', 'GCE_PROJECT') }}"
    credentials_file: "{{ lookup('env', 'GCE_PEM_FILE_PATH') }}"
    service_account_email: "{{ lookup('env', 'GCE_EMAIL') }}"

  tasks:
    - name: Create instance
      gce:
        instance_names: "{{ item }}"
        machine_type: "{{ machine_type }}"
        image: "{{ image }}"
        project_id: "{{ project_id }}"
        credentials_file: "{{ credentials_file }}"
        service_account_email: "{{ service_account_email }}"
      with_items: "{{ instances }}"
