---
- hosts: all
  gather_facts: no

  vars:
    project_id: "{{ lookup('env', 'GCE_PROJECT') }}"
    credentials_file: "{{ lookup('env', 'GCE_PEM_FILE_PATH') }}"
    service_account_email: "{{ lookup('env', 'GCE_EMAIL') }}"

  tasks:
    - gce_snapshot:
        instance_name: "{{ inventory_hostname }}"
        snapshot_name: "{{ inventory_hostname }}-demo"
        state: present
        project_id: "{{ project_id }}"
        credentials_file: "{{ credentials_file }}"
        service_account_email: "{{ service_account_email }}"
      delegate_to: localhost
