---
- name: Destroy the GCE instances
  hosts: localhost
  gather_facts: no
  connection: local

  vars:
    instances:
      - gcpdemo0
      - gcpdemo1
    project_id: "{{ lookup('env', 'GCE_PROJECT') }}"
    credentials_file: "{{ lookup('env', 'GCE_PEM_FILE_PATH') }}"
    service_account_email: "{{ lookup('env', 'GCE_EMAIL') }}"

  tasks:
    - name: Destroy GCE instances
      gce:
        instance_names: "{{ item }}"
        state: absent
        project_id: "{{ project_id }}"
        credentials_file: "{{ credentials_file }}"
        service_account_email: "{{ service_account_email }}"
      with_items: "{{ instances }}"

    - name: Remove DNS record
      gcdns_record:
        record: "{{ item }}.ansiblemeetup.com"
        zone: ansiblemeetup.com
        state: absent
        type: A
        overwrite: true
        project_id: "{{ project_id }}"
        credentials_file: "{{ credentials_file }}"
        service_account_email: "{{ service_account_email }}"
      with_items: "{{ instances }}"

    - name: Remove DNS zone
      gcdns_zone:
        zone: ansiblemeetup.com
        state: absent
        project_id: "{{ project_id }}"
        credentials_file: "{{ credentials_file }}"
        service_account_email: "{{ service_account_email }}"
